title: "RiceYak"
author: "Philipp Braun"
description: "Made with ❤️"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
url: "https://braunphilipp.github.io"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:3589810@gmail.com"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/BraunPhilipp"}
  - {title: Github, icon: github, url: "https://github.com/BraunPhilipp"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
